insert into employee(id, department,employee_name,employee_salary)
values(1, 'HR', 'Akshay', 100000);

insert into employee(id, department,employee_name,employee_salary)
values(2, 'Manager', 'Akki', 200000);

insert into employee(id, department,employee_name,employee_salary)
values(3, 'Engineer', 'neeva', 300000);

/*insert into todo(id, username,description,target_date,is_done)
values(10002, 'in28minutes', 'Learn Data JPA', sysdate(), false);

insert into todo(id, username,description,target_date,is_done)
values(10003, 'in28minutes', 'Learn Microservices', sysdate(), false);*/

/* create table employee (id bigint generated by default as identity, department varchar(255), employee_name varchar(255), employee_salary integer, primary key (id))*/